# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alcides/Code/Research/wool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alcides/Code/Research/wool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alcides/Code/Research/wool/CMakeFiles /Users/alcides/Code/Research/wool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alcides/Code/Research/wool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fib-wool

# Build rule for target.
fib-wool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fib-wool
.PHONY : fib-wool

# fast build rule for target.
fib-wool/fast:
	$(MAKE) -f CMakeFiles/fib-wool.dir/build.make CMakeFiles/fib-wool.dir/build
.PHONY : fib-wool/fast

benchmarks/fib/fib-wool.o: benchmarks/fib/fib-wool.c.o

.PHONY : benchmarks/fib/fib-wool.o

# target to build an object file
benchmarks/fib/fib-wool.c.o:
	$(MAKE) -f CMakeFiles/fib-wool.dir/build.make CMakeFiles/fib-wool.dir/benchmarks/fib/fib-wool.c.o
.PHONY : benchmarks/fib/fib-wool.c.o

benchmarks/fib/fib-wool.i: benchmarks/fib/fib-wool.c.i

.PHONY : benchmarks/fib/fib-wool.i

# target to preprocess a source file
benchmarks/fib/fib-wool.c.i:
	$(MAKE) -f CMakeFiles/fib-wool.dir/build.make CMakeFiles/fib-wool.dir/benchmarks/fib/fib-wool.c.i
.PHONY : benchmarks/fib/fib-wool.c.i

benchmarks/fib/fib-wool.s: benchmarks/fib/fib-wool.c.s

.PHONY : benchmarks/fib/fib-wool.s

# target to generate assembly for a file
benchmarks/fib/fib-wool.c.s:
	$(MAKE) -f CMakeFiles/fib-wool.dir/build.make CMakeFiles/fib-wool.dir/benchmarks/fib/fib-wool.c.s
.PHONY : benchmarks/fib/fib-wool.c.s

wool.o: wool.c.o

.PHONY : wool.o

# target to build an object file
wool.c.o:
	$(MAKE) -f CMakeFiles/fib-wool.dir/build.make CMakeFiles/fib-wool.dir/wool.c.o
.PHONY : wool.c.o

wool.i: wool.c.i

.PHONY : wool.i

# target to preprocess a source file
wool.c.i:
	$(MAKE) -f CMakeFiles/fib-wool.dir/build.make CMakeFiles/fib-wool.dir/wool.c.i
.PHONY : wool.c.i

wool.s: wool.c.s

.PHONY : wool.s

# target to generate assembly for a file
wool.c.s:
	$(MAKE) -f CMakeFiles/fib-wool.dir/build.make CMakeFiles/fib-wool.dir/wool.c.s
.PHONY : wool.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fib-wool"
	@echo "... benchmarks/fib/fib-wool.o"
	@echo "... benchmarks/fib/fib-wool.i"
	@echo "... benchmarks/fib/fib-wool.s"
	@echo "... wool.o"
	@echo "... wool.i"
	@echo "... wool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

